openapi: 3.2.0
info:
  title: SeekrFlow Version API
  description: SeekrFlow API Documentation
  termsOfService: http://www.seekr.com/support
  contact:
    name: Seekr API Support
    url: http://www.seekr.com/contact
    email: contact@seekr.com
  version: 0.1.0
servers:
- url: https://flow.seekr.com
  description: SeekrBuild server base URL
tags:
- name: Version
paths:
  /version:
    get:
      summary: Show Version
      operationId: show_version_version_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      x-excluded: true
      tags:
      - Version
components:
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      description: Your Seekr API key, sent in the Authorization header with no 'Bearer' prefix.
      in: header
      name: Authorization
